hermine/cube/urls.py
# SPDX-FileCopyrightText: 2021 Hermine-team <hermine@inno3.fr>
# SPDX-FileCopyrightText: 2022 Martin Delabre <gitlab.com/delabre.martin>
#
# SPDX-License-Identifier: AGPL-3.0-only
from django.urls import path, include
from rest_framework.authtoken import views as authviews
from rest_framework_nested import routers

from . import views, api_views

app_name = "cube"
urlpatterns = [
    path("", views.DashboardView.as_view(), name="dashboard"),
    path("about/", views.AboutView.as_view(), name="about"),
    # Product views
    path("products/", views.ProductListView.as_view(), name="product_list"),
    path(
        "products/<int:pk>/", views.ProductDetailView.as_view(), name="product_detail"
    ),
    path(
        "products/<int:product_pk>/new_release/",
        views.ReleaseCreateView.as_view(),
        name="release_create",
    ),
    path("products/new/", views.ProductCreateView.as_view(), name="product_create"),
    path(
        "products/<int:pk>/edit/",
        views.ProductUpdateView.as_view(),
        name="product_update",
    ),
    path(
        "products/<int:pk>/delete/",
        views.ProductDeleteView.as_view(),
        name="product_delete",
    ),
    # Product categories views
    path("categories/", views.CategoryListView.as_view(), name="category_list"),
    path(
        "categories/<int:pk>/",
        views.CategoryDetailView.as_view(),
        name="category_detail",
    ),
    path("categories/new/", views.CategoryCreateView.as_view(), name="category_create"),
    path(
        "categories/<int:pk>/edit/",
        views.CategoryUpdateView.as_view(),
        name="category_update",
    ),
    # Components views
    path("components/", views.ComponentListView.as_view(), name="component_list"),
    path(
        "components/popular/",
        views.ComponentPopularListView.as_view(),
        name="component_populars",
    ),
    path(
        "components/<int:pk>/",
        views.ComponentDetailView.as_view(),
        name="component_detail",
    ),
    path(
        "components/<int:pk>/edit/",
        views.ComponentUpdateView.as_view(),
        name="component_update",
    ),
    path(
        "components/<int:component_id>/update_funding/",
        views.component_update_funding,
        name="component_update_funding",
    ),
    path(
        "curations/",
        views.LicenseCurationListView.as_view(),
        name="licensecuration_list",
    ),
    path(
        "curations/new/",
        views.LicenseCurationCreateView.as_view(),
        name="licensecuration_create",
    ),
    path(
        "curations/edit/<int:pk>/",
        views.LicenseCurationUpdateView.as_view(),
        name="licensecuration_update",
    ),
    path(
        "curations/export/",
        views.LicenseCurationExportView.as_view(),
        name="licensecuration_export",
    ),
    path(
        "curations/<int:pk>/export/",
        views.LicenseCurationSingleExportView.as_view(),
        name="licensecuration_single_export",
    ),
    # Licenses and policy views
    path("licenses/", views.LicensesListView.as_view(), name="license_list"),
    path(
        "licenses/<int:pk>/", views.LicenseDetailView.as_view(), name="license_detail"
    ),
    path(
        "licenses/<int:pk>/edit/",
        views.LicenseDataUpdateView.as_view(),
        name="license_update",
    ),
    path(
        "licenses/<int:pk>/edit_policy/",
        views.LicensePolicyUpdateView.as_view(),
        name="license_update_policy",
    ),
    path("licenses/new/", views.LicenseCreateView.as_view(), name="license_create"),
    path(
        "licenses/<int:pk>/diff/", views.LicenseDiffView.as_view(), name="license_diff"
    ),
    path(
        "licenses/<int:pk>/diff_update/<str:field>/",
        views.LicenseDiffUpdateView.as_view(),
        name="license_diff_update",
    ),
    path("licenses/export/", views.LicenseExportView.as_view(), name="license_export"),
    path(
        "licenses/<int:license_id>/export/",
        views.LicenseSingleExportView.as_view(),
        name="license_export_single",
    ),
    path(
        "licenses/<int:pk>/print/",
        views.LicensePrintView.as_view(),
        name="license_print",
    ),
    path(
        "license/<int:license_pk>/new_obligation/",
        views.ObligationCreateView.as_view(),
        name="obligation_create",
    ),
    path(
        "obligations/<int:pk>/edit/",
        views.ObligationUpdateView.as_view(),
        name="obligation_update",
    ),
    path(
        "obligations/<int:pk>/delete/",
        views.ObligationDeleteView.as_view(),
        name="obligation_delete",
    ),
    path(
        "obligations/<int:pk>/diff_update/<str:field>/",
        views.ObligationDiffUpdateView.as_view(),
        name="obligation_diff_update",
    ),
    path(
        "obligations/orphans/",
        views.ObligationsListView.as_view(),
        name="obligations_orphans",
    ),
    path("generics/", views.GenericListView.as_view(), name="generic_list"),
    path(
        "generics/<int:pk>/", views.GenericDetailView.as_view(), name="generic_detail"
    ),
    path("generics/new/", views.GenericCreateView.as_view(), name="generic_create"),
    path(
        "generics/<int:pk>/edit/",
        views.GenericUpdateView.as_view(),
        name="generic_update",
    ),
    path(
        "generics/<int:pk>/diff/", views.GenericDiffView.as_view(), name="generic_diff"
    ),
    path(
        "generics/<int:pk>/diff_update/<str:field>/",
        views.GenericDiffUpdateView.as_view(),
        name="generic_diff_update",
    ),
    path("generics/export/", views.GenericExportView.as_view(), name="generic_export"),
    # License policy views
    path(
        "authorized_contexts/",
        views.AuthorizedContextListView.as_view(),
        name="authorizedcontext_list",
    ),
    path(
        "licenses/<int:license_pk>/new_authorized_context/",
        views.AuthorizedContextCreateView.as_view(),
        name="authorizedcontext_create",
    ),
    path(
        "authorized_contexts/<int:pk>/edit/",
        views.AuthorizedContextUpdateView.as_view(),
        name="authorizedcontext_update",
    ),
    path(
        "derogations/",
        views.DerogationListView.as_view(),
        name="derogation_list",
    ),
    path(
        "licensechoices/",
        views.LicenseChoiceListView.as_view(),
        name="licensechoice_list",
    ),
    path(
        "licensechoices/<int:pk>/edit/",
        views.LicenseChoiceUpdateView.as_view(),
        name="licensechoice_update",
    ),
    path(
        "licensechoices/new/",
        views.LicenseChoiceCreateView.as_view(),
        name="licensechoice_create",
    ),
    path("shared/", views.SharedReferenceView.as_view(), name="shared_reference"),
    path(
        "shared/copy-licenses/",
        views.CopyReferenceLicensesView.as_view(),
        name="shared_licenses_copy",
    ),
    path(
        "shared/copy-generics/",
        views.CopyReferenceGenericsView.as_view(),
        name="shared_generics_copy",
    ),
    path(
        "shared/copy-obligation/",
        views.CopyReferenceObligationView.as_view(),
        name="shared_obligation_copy",
    ),
    path(
        "shared/sync-everything/",
        views.SyncEverythingFromReferenceView.as_view(),
        name="shared_sync_everything",
    ),
    # Releases views
    path(
        "releases/<int:pk>/edit/",
        views.ReleaseUpdateView.as_view(),
        name="release_update",
    ),
    path(
        "releases/<int:release_pk>/",
        views.ReleaseSummaryView.as_view(),
        name="release_summary",
    ),
    path(
        "releases/<int:pk>/import/",
        views.ReleaseImportView.as_view(),
        name="release_import",
    ),
    path(
        "releases/<int:release_pk>/bom/",
        views.ReleaseBomView.as_view(),
        name="release_bom",
    ),
    path(
        "releases/<int:pk>/bom/export/",
        views.ReleaseBomExportView.as_view(),
        name="release_bom_export",
    ),
    path(
        "releases/<int:pk>/obligations/",
        views.ReleaseObligationsView.as_view(),
        name="release_obligations",
    ),
    path(
        "releases/<int:release_pk>/obligations/<int:generic_id>/",
        views.ReleaseGenericView.as_view(),
        name="release_generic",
    ),
    path(
        "releases/<int:release_pk>/delete_usages/",
        views.ScopeUsagesDeleteView.as_view(),
        name="scope_usages_delete",
    ),
    # Usage views
    path(
        "releases/<int:release_pk>/new_usage/",
        views.UsageCreateView.as_view(),
        name="usage_create",
    ),
    path(
        "usages/<int:pk>/edit/",
        views.UsageUpdateView.as_view(),
        name="usage_update",
    ),
    path(
        "usages/<int:pk>/delete/",
        views.UsageDeleteView.as_view(),
        name="usage_delete",
    ),
    # Release validation related views
    path(
        "releases/<int:pk>/validation/",
        views.ReleaseValidationView.as_view(),
        name="release_validation",
    ),
    ## Step 1
    path(
        "usages/<int:usage_pk>/new_license_curation/",
        views.ReleaseLicenseCurationCreateView.as_view(),
        name="release_licensecuration_create",
    ),
    path(
        "release/<int:id>/validation/fixed_licenses/",
        views.ReleaseCuratedLicensesView.as_view(),
        name="release_curated_licenses",
    ),
    path(
        "usages/<int:pk>/update_license_curation/",
        views.UpdateLicenseCurationView.as_view(),
        name="release_update_license_curation",
    ),
    ### Step 2
    path(
        "usages/<int:usage_pk>/new_ands_validation/",
        views.ReleaseAndsValidationCreateView.as_view(),
        name="release_andsvalidation_create",
    ),
    path(
        "releases/<int:id>/validation/ands_validations/",
        views.ReleaseAndsConfirmationView.as_view(),
        name="release_ands_validations",
    ),
    path(
        "usages/<int:pk>/update_ands_validation/",

hermine/hermine/urls.py
# SPDX-FileCopyrightText: 2021 Hermine-team <hermine@inno3.fr>
# SPDX-FileCopyrightText: 2022 Martin Delabre <gitlab.com/delabre.martin>
#
# SPDX-License-Identifier: AGPL-3.0-only

"""hermine URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.conf import settings
from django.db import connection, Error as DBError
from django.http import HttpResponse, HttpResponseServerError
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Hermine API",
        default_version="v1",
        description="Hermine Rest API documentation",
        # terms_of_service="https://hermine-foss.org/",
        contact=openapi.Contact(email="hermine@inno3.fr"),
        license=openapi.License(name="AGPL-3.0-only"),
    ),
    public=False,
    permission_classes=[
        permissions.IsAuthenticated,
    ],
)


def ready(r):
    try:
        with connection.cursor() as cursor:
            cursor.execute("SELECT 1;")
            row = cursor.fetchone()
            if row is None:
                return HttpResponseServerError("Database: invalid response")
    except DBError:
        return HttpResponseServerError("Database: cannot connect")

    return HttpResponse("OK")


urlpatterns = [
    path("", include("cube.urls")),
    path("ping/", lambda r: HttpResponse("OK")),
    path("ready/", ready),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
    re_path(
        r"^api-doc(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^api-doc-swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    re_path(
        r"^api-doc/$",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

if settings.ENABLE_PROFILING:
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

hermine/cube/models/products.py
#  SPDX-FileCopyrightText: 2021 Hermine-team <hermine@inno3.fr>
#
#  SPDX-License-Identifier: AGPL-3.0-only

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse_lazy


class Product(models.Model):
    """
    A product which dependencies are to be audited.
    """

    name = models.CharField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    categories = models.ManyToManyField(
        "Category", db_table="cube_category_products", blank=True
    )

    def get_absolute_url(self):
        return reverse_lazy("cube:product_detail", args=[self.id])

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name = "Product"
        verbose_name_plural = "Products"


class Category(models.Model):
    """
    A category of product
    """

    name = models.CharField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def get_absolute_url(self):
        return reverse_lazy("cube:category_detail", args=[self.id])

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Product category"
        verbose_name_plural = "Product categories"


class Release(models.Model):
    """
    A specific release of a product
    """

    SHIPPING_CHOICES = [
        ("Archived", "Archived"),
        ("Active", "In developpement"),
        ("Published", "Published"),
    ]
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="releases"
    )
    release_number = models.CharField(
        max_length=200, help_text="Must be unique for a product"
    )
    ship_status = models.CharField(max_length=20, choices=SHIPPING_CHOICES, blank=True)
    pub_date = models.DateTimeField("date published", blank=True, null=True)
    # Last completed step, 0 when none is validated
    valid_step = models.IntegerField("Validation Step", default=0)
    commit = models.CharField("Commit hash or ref", max_length=255, blank=True)

    def get_absolute_url(self):
        return reverse_lazy("cube:release_summary", args=[self.id])

    def __str__(self):
        return self.product.__str__() + " " + self.release_number

    class Meta:
        ordering = ["product", "release_number"]
        unique_together = ["product", "release_number"]
        verbose_name = "Product release"
        verbose_name_plural = "Product releases"
        permissions = [
            ("change_release_bom", "Can upload a new BOM for a release"),
        ]


class Exploitation(models.Model):
    """
    Stores how a release is exploited (so all its Usage can be updated accordingly)
    """

    from cube.models.components import Usage

    release = models.ForeignKey(
        Release, on_delete=models.CASCADE, related_name="exploitations"
    )
    scope = models.CharField(
        max_length=50, blank=True, help_text="Leave blank to apply for any scope"
    )
    project = models.CharField(
        max_length=750, blank=True, help_text="Leave blank to apply for any project"
    )
    exploitation = models.CharField(
        max_length=50,
        choices=Usage.EXPLOITATION_CHOICES,
        default=Usage.EXPLOITATION_DISTRIBUTION_BOTH,
    )

    def __str__(self):
        return self.release.__str__() + " : " + str(self.scope)

    class Meta:
        unique_together = ["release", "scope", "project"]

hermine/cube/views/misc.py
#  SPDX-FileCopyrightText: 2021 Hermine-team <hermine@inno3.fr>
#  SPDX-FileCopyrightText: 2022 Martin Delabre <gitlab.com/delabre.martin>
#
#  SPDX-License-Identifier: AGPL-3.0-only


from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from cube.models import License, Product, Component, Release, Generic
from cube.models.meta import ReleaseConsultation


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "cube/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["last_releases"] = (
            rc.release
            for rc in ReleaseConsultation.objects.filter(user=self.request.user)
            .prefetch_related("release")
            .order_by("-date")[:10]
        )
        context["products_count"] = Product.objects.all().count()
        context["releases_count"] = Release.objects.all().count()
        context["components_count"] = Component.objects.all().count()
        context["licenses_count"] = License.objects.all().count()
        context["generics_count"] = Generic.objects.all().count()
        kwargs.update(context)

        return kwargs


class AboutView(TemplateView):
    template_name = "cube/about.html"

hermine/cube/templates/cube/cube.html
<!--
SPDX-FileCopyrightText: Viktor Kuzhelny https://github.com/vikdiesel/admin-one-bulma-dashboard/
SPDX-FileCopyrightText: 2021 Hermine-team <hermine@inno3.fr>
SPDX-FileCopyrightText: 2022 Martin Delabre <gitlab.com/delabre.martin>
SPDX-License-Identifier: MIT
-->
<!DOCTYPE html>
<html lang="en" class="has-aside-left has-aside-mobile-transition has-navbar-fixed-top has-aside-expanded">
  <head>
    {% load static %}
    <!-- Fonts -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'favicon.ico' %}">
    {% include "hermine/index.html" %}
    <title>{% block title %}{% endblock %} - Hermine
    </title>
  </head>
  <body>
    <div id="app">
      <nav id="navbar-main" class="navbar is-fixed-top">
        <div class="navbar-brand">
          <a class="navbar-item is-hidden-desktop jb-aside-mobile-toggle">
            <span class="icon">
              <i class="fas fa-bars">
              </i>
            </span>
          </a>
        </div>
        <div class="navbar-brand is-right">
          <a class="navbar-item is-hidden-desktop jb-navbar-menu-toggle" data-target="navbar-menu">
            <span class="icon"><i class="fas fa-ellipsis-v"></i></span>
          </a>
        </div>
        <div class="navbar-menu fadeIn animated faster" id="navbar-menu">
          <div class="navbar-end">
            <div class="navbar-item"><span class="icon"><i class="fas fa-users"></i></span> {% for group in user.groups.all %} {{ group }} {%endfor%}</div>
            <div class="navbar-item">
              <div class="is-user-avatar">
                <span class="icon"><i class="fas fa-user"></i></span>
              </div>
              <div class="is-user-name">
                <span>{%if user.first_name or user.last_name %}{{user.first_name}} {{user.last_name}}{%else%}{{user.username}}{%endif%}
                </span>
              </div>
            </div>
            <form class="navbar-item" method="post" action="{% url 'logout' %}">{% csrf_token %}
              <button class="button  is-desktop-icon-only" type="submit">
                <span class="icon"><i class="fas fa-sign-out-alt"></i>
                </span>
                <span>Logout</span>
              </button>
            </form>
          </div>
        </div>
      </nav>
      <aside class="aside is-placed-left is-expanded">
        <div class="aside-tools">
          <div class="aside-tools-label">
            <span><b>Hermine</b></span>
          </div>
        </div>
        <div class="menu is-menu-main">
          <p class="menu-label">General</p>
          <ul class="menu-list">
            <li>
              <a href="{% url 'cube:dashboard' %}" class="has-icon">
                <span class="icon"><i class="fas fa-chart-pie"></i></span>
                <span class="menu-item-label">Dashboard</span>
              </a>
            </li>
          </ul>
          {% if perms.cube.view_product or perms.cube.view_category or perms.cube.view_component or perms.cube.view_licensecuration %}
            <p class="menu-label">Development</p>
            <ul class="menu-list">
              {% if perms.cube.view_product or perms.cube.view_category %}
                <li>
                  <a class="has-icon has-dropdown-icon">
                    <span class="icon"><i class="fas fa-cubes"></i></span>
                    <span class="menu-item-label">Your products</span>
                    <div class="dropdown-icon">
                      <span class="icon"><i class="fas fa-caret-right"></i></span>
                    </div>
                  </a>
                  <ul>
                    {% if perms.cube.view_product %}
                      <li>
                        <a href="{% url 'cube:product_list' %}">
                          <span>All products</span>
                        </a>
                      </li>
                    {% endif %}
                    {% if perms.cube.view_category %}
                      <li>
                        <a href="{% url 'cube:category_list' %}">
                          <span>Product categories</span>
                        </a>
                      </li>
                    {% endif %}
                  </ul>
                </li>
              {% endif %}
              {% if perms.cube.view_component or perms.cube.view_licensecuration %}
                <li>
                  <a class="has-icon has-dropdown-icon">
                    <span class="icon"><i class="fas fa-puzzle-piece"></i></span>
                    <span class="menu-item-label">Components</span>
                    <div class="dropdown-icon">
                      <span class="icon"><i class="fas fa-caret-right"></i></span>
                    </div>
                  </a>
                  <ul>
                    {% if perms.cube.view_component %}
                      <li>
                        <a href="{% url 'cube:component_list' %}">
                          <span>Complete List</span>
                        </a>
                      </li>
                      <li>
                        <a href="{% url 'cube:component_populars' %}">
                          <span>Most used ones</span>
                        </a>
                      </li>
                    {% endif %}
                    {% if perms.cube.view_licensecuration %}
                      <li>
                        <a href="{% url 'cube:licensecuration_list' %}">
                          <span>Curations</span>
                        </a>
                      </li>
                    {% endif %}
                  </ul>
                </li>
              {% endif %}
            </ul>
          {% endif %}
          <p class="menu-label">Legal
          </p>
          <ul class="menu-list">
            {% if perms.cube.view_license %}
              <li>
                <a href="{% url 'cube:license_list' %}" class="has-icon">
                  <span class="icon">
                    <i class="fas fa-balance-scale">
                    </i>
                  </span>
                  <span class="menu-item-label">Licenses
                  </span>
                </a>
              </li>
            {% endif %}
            {% if perms.cube.view_generic %}
              <li>
                <a href="{% url 'cube:generic_list' %}" class=" has-icon">
                  <span class="icon">
                    <i class="fas fa-award">
                    </i>
                  </span>
                  <span class="menu-item-label">Generic obligations
                  </span>
                </a>
              </li>
            {% endif %}
            {% if perms.cube.view_derogation %}
              <li>
                <a href="{% url 'cube:authorizedcontext_list' %}" class=" has-icon">
                  <span class="icon">
                    <i class="fas fa-clipboard-check">
                    </i>
                  </span>
                  <span class="menu-item-label">Authorized contexts
                  </span>
                </a>
              </li>
              <li>
                <a href="{% url 'cube:derogation_list' %}" class=" has-icon">
                  <span class="icon">
                    <i class="fas fa-clipboard-check">
                    </i>
                  </span>
                  <span class="menu-item-label">Specific derogations
                  </span>
                </a>
              </li>
            {% endif %}
            {% if perms.cube.view_licensechoice %}
              <li>
                <a href="{% url 'cube:licensechoice_list' %}" class=" has-icon">
                  <span class="icon">
                    <i class="fas fa-project-diagram">
                    </i>
                  </span>
                  <span class="menu-item-label">License choices
                  </span>
                </a>
              </li>
            {% endif %}
            {% if perms.cube.view_license and is_shared_reference_loaded %}
              <li>
                <a href="{% url 'cube:shared_reference' %}" class="has-icon">
                  <span class="icon">
                    <i class="fas fa-share-alt">
                    </i>
                  </span>
                  <span class="menu-item-label">Shared reference
                  </span>
                </a>
              </li>
            {% endif %}
          </ul>
          {% if user.is_staff %}
            <p class="menu-label">Tools
            </p>
            <ul class="menu-list">
              <li>
                <a href="{% url 'schema-redoc' %}" class="has-icon">
                  <span class="icon">
                    <i class="fas fa-database">
                    </i>
                  </span>
                  <span class="menu-item-label">API
                  </span>
                </a>
              </li>
              <li>
                <a href="{% url 'admin:index' %}" class="has-icon">
                  <span class="icon">
                    <i class="fas fa-cogs">
                    </i>
                  </span>
                  <span class="menu-item-label">Django Admin
                  </span>
                </a>
              </li>
              <li>
                <a href="https://docs.hermine-foss.org/" class="has-icon" target="_blank">
                  <span class="icon">
                    <i class="fas fa-book">
                    </i>
                  </span>
                  <span class="menu-item-label">Documentation
                  </span>
                </a>
              </li>
              <li>
                <a href="{% url 'cube:about' %}" class="has-icon">
                  <span class="icon">
                    <i class="far fa-question-circle">
                    </i>
                  </span>
                  <span class="menu-item-label">About
                  </span>
                </a>
              </li>
            </ul>
          {% endif %}
        </div>
      </aside>
      <section class="section is-title-bar">
        <div class="level">
          <div class="level-left">
            <div class="level-item">
              {% block breadcrumbs %}
              {% endblock %}
            </div>
          </div>
          <div class="level-right">
            <div class="level-item">
              {% block actions %}
              {% endblock %}
            </div>
          </div>
        </div>
      </section>
      <section class="hero is-hero-bar is-small">
        <div class="hero-body">
          <div class="level">
            <div class="level-left">
              <div class="level-item">
                {% block herozone %}
                {% endblock %}
              </div>
            </div>
            <div class="level-right">
              <div class="level-item">
                {% block infoitem %}
                {% endblock %}
              </div>
            </div>
          </div>
        </div>
      </section>
      <section class="section is-main-section content">
        {% block content %}
        {% endblock %}
      </section>
      <footer class="footer">
        <div class="container-fluid">
          <div class="level">
            <div class="level-left">
              <div class="level-item">
                © 2021, Hermine project contributors
              </div>
              <div class="level-item">
                <a href="https://gitlab.com/hermine-project/hermine" style="height: 20px">
                  <img src="{% static 'cube/media/agpl.svg' %}" alt="AGPL-3.0 License">
                </a>
              </div>
            </div>
            <div class="level-right">
              <div class="level-item">
                {% load version %}
                <span class='version'>{% version %}</span>
              </div>
              <div class="level-item">
                <div class="logo">
                  <a href="https://hermine-foss.org">
                    <img src="{% static 'cube/media/LogoHermine.svg' %}" alt="Hermine project Logo">
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>

hermine/cube/templates/cube/release_import.html
<!--
SPDX-FileCopyrightText: 2021 Hermine-team <hermine@inno3.fr>
SPDX-FileCopyrightText: 2022 Martin Delabre <gitlab.com/delabre.martin>

SPDX-License-Identifier: AGPL-3.0-only
-->

{% extends "cube/cube.html" %}
{% block title %}{{ object.product.name }} {{object.release_number}}{% endblock %}
{% block breadcrumbs %}
  <ul>
    <li><a href="{% url 'cube:dashboard' %}">Hermine</a></li>
    <li><a href="{% url 'cube:product_detail' object.product.id %}">{{ object.product.name }}</a></li>
    <li>{{object.release_number}}</li>
    <li> Import components</li>
  </ul>
{% endblock %}
{% block herozone %}
  <div class="hero-body">
    <p class="title">Release: {{object.release_number}} - Import components into this release</p>
  </div>
{% endblock %}
{% block content %}
  {% include "cube/includes/release_tabs.html" with active_tab="import" %}

  {% if messages %}
    {% for message in messages %}
      <div class="notification is-{{ message.tags }} is-light">{{ message }}
      </div>
    {% endfor %}
  {% endif %}
  <div class="card">
    <div class="card-content">
      <h3>Import BOM</h3>
      <form action="{% url 'cube:release_import' release.id %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form }}
        {% include "cube/includes/bulma_submit.html" with label="Import now" %}
      </form>
    </div>
  </div>
  <div class="card">
    <div class="card-content">
      <h3>Add single component</h3>
      You can also <a href="{% url 'cube:usage_create' release.id %}">add an individual component</a> to the release.
    </div>
  </div>

{% endblock %}