hermine/cube/urls.py
# SPDX-FileCopyrightText: 2021 Hermine-team <hermine@inno3.fr>
# SPDX-FileCopyrightText: 2022 Martin Delabre <gitlab.com/delabre.martin>
#
# SPDX-License-Identifier: AGPL-3.0-only
from django.urls import path, include
from rest_framework.authtoken import views as authviews
from rest_framework_nested import routers

from . import views, api_views

app_name = "cube"
urlpatterns = [
    path("", views.DashboardView.as_view(), name="dashboard"),
    path("about/", views.AboutView.as_view(), name="about"),
    # Product views
    path("products/", views.ProductListView.as_view(), name="product_list"),
    path(
        "products/<int:pk>/", views.ProductDetailView.as_view(), name="product_detail"
    ),
    path(
        "products/<int:product_pk>/new_release/",
        views.ReleaseCreateView.as_view(),
        name="release_create",
    ),
    path("products/new/", views.ProductCreateView.as_view(), name="product_create"),
    path(
        "products/<int:pk>/edit/",
        views.ProductUpdateView.as_view(),
        name="product_update",
    ),
    path(
        "products/<int:pk>/delete/",
        views.ProductDeleteView.as_view(),
        name="product_delete",
    ),
    # Product categories views
    path("categories/", views.CategoryListView.as_view(), name="category_list"),
    path(
        "categories/<int:pk>/",
        views.CategoryDetailView.as_view(),
        name="category_detail",
    ),
    path("categories/new/", views.CategoryCreateView.as_view(), name="category_create"),
    path(
        "categories/<int:pk>/edit/",
        views.CategoryUpdateView.as_view(),
        name="category_update",
    ),
    # Components views
    path("components/", views.ComponentListView.as_view(), name="component_list"),
    path(
        "components/popular/",
        views.ComponentPopularListView.as_view(),
        name="component_populars",
    ),
    path(
        "components/<int:pk>/",
        views.ComponentDetailView.as_view(),
        name="component_detail",
    ),
    path(
        "components/<int:pk>/edit/",
        views.ComponentUpdateView.as_view(),
        name="component_update",
    ),
    path(
        "components/<int:component_id>/update_funding/",
        views.component_update_funding,
        name="component_update_funding",
    ),
    path(
        "curations/",
        views.LicenseCurationListView.as_view(),
        name="licensecuration_list",
    ),
    path(
        "curations/new/",
        views.LicenseCurationCreateView.as_view(),
        name="licensecuration_create",
    ),
    path(
        "curations/edit/<int:pk>/",
        views.LicenseCurationUpdateView.as_view(),
        name="licensecuration_update",
    ),
    path(
        "curations/export/",
        views.LicenseCurationExportView.as_view(),
        name="licensecuration_export",
    ),
    path(
        "curations/<int:pk>/export/",
        views.LicenseCurationSingleExportView.as_view(),
        name="licensecuration_single_export",
    ),
    # Licenses and policy views
    path("licenses/", views.LicensesListView.as_view(), name="license_list"),
    path(
        "licenses/<int:pk>/", views.LicenseDetailView.as_view(), name="license_detail"
    ),
    path(
        "licenses/<int:pk>/edit/",
        views.LicenseDataUpdateView.as_view(),
        name="license_update",
    ),
    path(
        "licenses/<int:pk>/edit_policy/",
        views.LicensePolicyUpdateView.as_view(),
        name="license_update_policy",
    ),
    path("licenses/new/", views.LicenseCreateView.as_view(), name="license_create"),
    path(
        "licenses/<int:pk>/diff/", views.LicenseDiffView.as_view(), name="license_diff"
    ),
    path(
        "licenses/<int:pk>/diff_update/<str:field>/",
        views.LicenseDiffUpdateView.as_view(),
        name="license_diff_update",
    ),
    path("licenses/export/", views.LicenseExportView.as_view(), name="license_export"),
    path(
        "licenses/<int:license_id>/export/",
        views.LicenseSingleExportView.as_view(),
        name="license_export_single",
    ),
    path(
        "licenses/<int:pk>/print/",
        views.LicensePrintView.as_view(),
        name="license_print",
    ),
    path(
        "license/<int:license_pk>/new_obligation/",
        views.ObligationCreateView.as_view(),
        name="obligation_create",
    ),
    path(
        "obligations/<int:pk>/edit/",
        views.ObligationUpdateView.as_view(),
        name="obligation_update",
    ),
    path(
        "obligations/<int:pk>/delete/",
        views.ObligationDeleteView.as_view(),
        name="obligation_delete",
    ),
    path(
        "obligations/<int:pk>/diff_update/<str:field>/",
        views.ObligationDiffUpdateView.as_view(),
        name="obligation_diff_update",
    ),
    path(
        "obligations/orphans/",
        views.ObligationsListView.as_view(),
        name="obligations_orphans",
    ),
    path("generics/", views.GenericListView.as_view(), name="generic_list"),
    path(
        "generics/<int:pk>/", views.GenericDetailView.as_view(), name="generic_detail"
    ),
    path("generics/new/", views.GenericCreateView.as_view(), name="generic_create"),
    path(
        "generics/<int:pk>/edit/",
        views.GenericUpdateView.as_view(),
        name="generic_update",
    ),
    path(
        "generics/<int:pk>/diff/", views.GenericDiffView.as_view(), name="generic_diff"
    ),
    path(
        "generics/<int:pk>/diff_update/<str:field>/",
        views.GenericDiffUpdateView.as_view(),
        name="generic_diff_update",
    ),
    path("generics/export/", views.GenericExportView.as_view(), name="generic_export"),
    # License policy views
    path(
        "authorized_contexts/",
        views.AuthorizedContextListView.as_view(),
        name="authorizedcontext_list",
    ),
    path(
        "licenses/<int:license_pk>/new_authorized_context/",
        views.AuthorizedContextCreateView.as_view(),
        name="authorizedcontext_create",
    ),
    path(
        "authorized_contexts/<int:pk>/edit/",
        views.AuthorizedContextUpdateView.as_view(),
        name="authorizedcontext_update",
    ),
    path(
        "derogations/",
        views.DerogationListView.as_view(),
        name="derogation_list",
    ),
    path(
        "licensechoices/",
        views.LicenseChoiceListView.as_view(),
        name="licensechoice_list",
    ),
    path(
        "licensechoices/<int:pk>/edit/",
        views.LicenseChoiceUpdateView.as_view(),
        name="licensechoice_update",
    ),
    path(
        "licensechoices/new/",
        views.LicenseChoiceCreateView.as_view(),
        name="licensechoice_create",
    ),
    path("shared/", views.SharedReferenceView.as_view(), name="shared_reference"),
    path(
        "shared/copy-licenses/",
        views.CopyReferenceLicensesView.as_view(),
        name="shared_licenses_copy",
    ),
    path(
        "shared/copy-generics/",
        views.CopyReferenceGenericsView.as_view(),
        name="shared_generics_copy",
    ),
    path(
        "shared/copy-obligation/",
        views.CopyReferenceObligationView.as_view(),
        name="shared_obligation_copy",
    ),
    path(
        "shared/sync-everything/",
        views.SyncEverythingFromReferenceView.as_view(),
        name="shared_sync_everything",
    ),
    # Releases views
    path(
        "releases/<int:pk>/edit/",
        views.ReleaseUpdateView.as_view(),
        name="release_update",
    ),
    path(
        "releases/<int:release_pk>/",
        views.ReleaseSummaryView.as_view(),
        name="release_summary",
    ),
    path(
        "releases/<int:pk>/import/",
        views.ReleaseImportView.as_view(),
        name="release_import",
    ),
    path(
        "releases/<int:release_pk>/bom/",
        views.ReleaseBomView.as_view(),
        name="release_bom",
    ),
    path(
        "releases/<int:pk>/bom/export/",
        views.ReleaseBomExportView.as_view(),
        name="release_bom_export",
    ),
    path(
        "releases/<int:pk>/obligations/",
        views.ReleaseObligationsView.as_view(),
        name="release_obligations",
    ),
    path(
        "releases/<int:release_pk>/obligations/<int:generic_id>/",
        views.ReleaseGenericView.as_view(),
        name="release_generic",
    ),
    path(
        "releases/<int:release_pk>/delete_usages/",
        views.ScopeUsagesDeleteView.as_view(),
        name="scope_usages_delete",
    ),
    # Usage views
    path(
        "releases/<int:release_pk>/new_usage/",
        views.UsageCreateView.as_view(),
        name="usage_create",
    ),
    path(
        "usages/<int:pk>/edit/",
        views.UsageUpdateView.as_view(),
        name="usage_update",
    ),
    path(
        "usages/<int:pk>/delete/",
        views.UsageDeleteView.as_view(),
        name="usage_delete",
    ),
    # Release validation related views
    path(
        "releases/<int:pk>/validation/",
        views.ReleaseValidationView.as_view(),
        name="release_validation",
    ),
    ## Step 1
    path(
        "usages/<int:usage_pk>/new_license_curation/",
        views.ReleaseLicenseCurationCreateView.as_view(),
        name="release_licensecuration_create",
    ),
    path(
        "release/<int:id>/validation/fixed_licenses/",
        views.ReleaseCuratedLicensesView.as_view(),
        name="release_curated_licenses",
    ),
    path(
        "usages/<int:pk>/update_license_curation/",
        views.UpdateLicenseCurationView.as_view(),
        name="release_update_license_curation",
    ),
    ### Step 2
    path(
        "usages/<int:usage_pk>/new_ands_validation/",
        views.ReleaseAndsValidationCreateView.as_view(),
        name="release_andsvalidation_create",
    ),
    path(
        "releases/<int:id>/validation/ands_validations/",
        views.ReleaseAndsConfirmationView.as_view(),
        name="release_ands_validations",
    ),
    path(
        "usages/<int:pk>/update_ands_validation/",

hermine/hermine/urls.py
# SPDX-FileCopyrightText: 2021 Hermine-team <hermine@inno3.fr>
# SPDX-FileCopyrightText: 2022 Martin Delabre <gitlab.com/delabre.martin>
#
# SPDX-License-Identifier: AGPL-3.0-only

"""hermine URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.conf import settings
from django.db import connection, Error as DBError
from django.http import HttpResponse, HttpResponseServerError
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Hermine API",
        default_version="v1",
        description="Hermine Rest API documentation",
        # terms_of_service="https://hermine-foss.org/",
        contact=openapi.Contact(email="hermine@inno3.fr"),
        license=openapi.License(name="AGPL-3.0-only"),
    ),
    public=False,
    permission_classes=[
        permissions.IsAuthenticated,
    ],
)


def ready(r):
    try:
        with connection.cursor() as cursor:
            cursor.execute("SELECT 1;")
            row = cursor.fetchone()
            if row is None:
                return HttpResponseServerError("Database: invalid response")
    except DBError:
        return HttpResponseServerError("Database: cannot connect")

    return HttpResponse("OK")


urlpatterns = [
    path("", include("cube.urls")),
    path("ping/", lambda r: HttpResponse("OK")),
    path("ready/", ready),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
    re_path(
        r"^api-doc(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^api-doc-swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    re_path(
        r"^api-doc/$",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

if settings.ENABLE_PROFILING:
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

hermine/cube/forms/mixins.py
#  SPDX-FileCopyrightText: 2021 Hermine-team <hermine@inno3.fr>
#
#  SPDX-License-Identifier: AGPL-3.0-only
from cube.forms.widgets import AutocompleteWidget, AutocompleteMultipleWidget


class AutocompleteFormMixin:
    def __init_subclass__(cls, **kwargs):
        for field in cls.Meta.autocomplete_fields:
            cls.Meta.widgets = getattr(cls.Meta, "widgets", {})
            if cls.Meta.model._meta.get_field(field).many_to_many:
                cls.Meta.widgets[field] = AutocompleteMultipleWidget(
                    cls.Meta.model._meta.get_field(field)
                )
            else:
                cls.Meta.widgets[field] = AutocompleteWidget(
                    cls.Meta.model._meta.get_field(field)
                )

        super().__init_subclass__(**kwargs)

hermine/cube/views/components.py
# SPDX-FileCopyrightText: 2021 Hermine-team <hermine@inno3.fr>
# SPDX-FileCopyrightText: 2022 Martin Delabre <gitlab.com/delabre.martin>
#
# SPDX-License-Identifier: AGPL-3.0-only

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Count
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import get_object_or_404, redirect

from cube.forms.components import LicenseCurationCreateForm, LicenseCurationUpdateForm
from cube.models import Component, LicenseCuration, Funding
from cube.views.mixins import SearchMixin, SaveAuthorMixin, QuerySuccessUrlMixin
from cube.utils.funding import get_fundings_from_purl


class ComponentListView(
    LoginRequiredMixin, PermissionRequiredMixin, SearchMixin, generic.ListView
):
    permission_required = "cube.view_component"
    model = Component
    template_name = "cube/component_list.html"
    paginate_by = 30
    ordering = ["name"]
    search_fields = ("name", "description", "spdx_expression")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        populars = Component.objects.annotate(
            popularity=Count("versions__usage__id")
        ).order_by("-popularity")[:10]
        context["populars"] = populars
        return context


class ComponentPopularListView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.ListView
):
    permission_required = "cube.view_component"
    model = Component
    template_name = "cube/component_popular.html"

    def get_queryset(self):
        return Component.objects.annotate(
            popularity=Count("versions__usage__id")
        ).order_by("-popularity")[:50]


class ComponentDetailView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView
):
    permission_required = "cube.view_component"
    template_name = "cube/component_detail.html"
    model = Component


class ComponentUpdateView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView
):
    permission_required = "cube.change_component"
    model = Component
    template_name = "cube/component_update.html"
    fields = [
        "name",
        "purl_type",
        "description",
        "programming_language",
        "spdx_expression",
        "homepage_url",
    ]

    def get_success_url(self):
        return reverse_lazy("cube:component_detail", args=[self.object.id])


class LicenseCurationListView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.ListView
):
    permission_required = "cube.view_licensecuration"
    paginate_by = 50
    model = LicenseCuration
    template_name = "cube/licensecuration_list.html"


class LicenseCurationCreateView(
    LoginRequiredMixin, PermissionRequiredMixin, SaveAuthorMixin, generic.CreateView
):
    permission_required = "cube.add_licensecuration"
    model = LicenseCuration
    template_name = "cube/licensecuration_form.html"
    form_class = LicenseCurationCreateForm
    success_url = reverse_lazy("cube:licensecuration_list")


class LicenseCurationUpdateView(
    LoginRequiredMixin,
    PermissionRequiredMixin,
    SaveAuthorMixin,
    QuerySuccessUrlMixin,
    generic.UpdateView,
):
    permission_required = "cube.change_licensecuration"
    model = LicenseCuration
    template_name = "cube/licensecuration_form.html"
    form_class = LicenseCurationUpdateForm
    success_url = reverse_lazy("cube:licensecuration_list")


@login_required
@permission_required("cube.change_component")
def component_update_funding(request, component_id):
    component = get_object_or_404(Component, pk=component_id)
    fundings = None
    versions = component.versions.all()
    version = versions[0]
    purl = version.purl
    if purl:
        fundings = get_fundings_from_purl(purl)
    if fundings:
        for funding in fundings:
            new_funding, created = Funding.objects.get_or_create(
                component=component,
                url=funding["url"],
                defaults={"type": funding["type"]},
            )
    return redirect(reverse_lazy("cube:component_detail", args=[component_id]))

hermine/cube/templates/cube/includes/bulma_submit.html
<!--
SPDX-FileCopyrightText: 2024 Hermine-team <hermine@inno3.fr>
SPDX-License-Identifier: AGPL-3.0-only
-->
<div class="field is-horizontal">
  <div class="field-label"></div>
  <div class="field-body">
    <div class="field">
      <div class="control">
        <button type="submit" class="button is-primary">{{ label|default:"Save" }}</button>
      </div>
    </div>
  </div>
</div>

hermine/cube/templates/cube/includes/default_form.html
<!--
SPDX-FileCopyrightText: 2023 Hermine-team <hermine@inno3.fr>
SPDX-License-Identifier: AGPL-3.0-only
-->
<form method="post" style="max-width: 50rem">
  {% csrf_token %}
  {{ form }}
  {{ form.media }}
  {% include "cube/includes/bulma_submit.html" with label="Save" %}
</form>

hermine/cube/templates/cube/includes/list_nav.html
<!--
SPDX-FileCopyrightText: 2022 Hermine-team <hermine@inno3.fr>
SPDX-License-Identifier: AGPL-3.0-only
-->
<div class="level">
  <div class="level-left">
    <div class="level-item">
      <form>
        <div class="field has-addons">
          <div class="control">
            <label class="is-sr-only" for="search_field">Search</label>
            <input id="search_field" class="input" name="search" placeholder="Search" value="{{ query }}" />
          </div>
          <div class="control">
            <button class="button" type="submit">Search</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  <div class="level-right">
    <div class="level-item">
      <nav class="pagination" role="navigation" aria-label="Pagination">
        <ul class="pagination-list">
          {% if page_obj.number > 2 %}
            <li>
              <a class="pagination-link"
                 href="?page=1&search={{ query }}"
                 aria-label="Go to first page"
              >
                1
              </a>
            </li>
          {% endif %}
          {% if page_obj.number > 3 %}
            <li>
              <span class="pagination-ellipsis">&hellip;</span>
            </li>
          {% endif %}
          {% if page_obj.has_previous %}
            <li>
              <a class="pagination-link"
                 href="?page={{ page_obj.previous_page_number }}&search={{ query }}"
                 aria-label="Go to page {{ page_obj.previous_page_number }}"
              >
                {{ page_obj.previous_page_number }}
              </a>
            </li>
          {% endif %}
          <li>
            <a class="pagination-link is-current" aria-label="Page {{ page_obj.number }}" aria-current="page">
              {{ page_obj.number }}
            </a>
          </li>
          {% if page_obj.has_next %}
            <li>
              <a class="pagination-link"
                 href="?page={{ page_obj.next_page_number }}&search={{ query }}"
                 aria-label="Go to page {{ page_obj.next_page_number }}"
              >
                {{ page_obj.next_page_number }}
              </a>
            </li>
          {% endif %}
          {% if page_obj.number < page_obj.paginator.num_pages|add:"-2" %}
            <li>
              <span class="pagination-ellipsis">&hellip;</span>
            </li>
          {% endif %}
          {% if page_obj.number < page_obj.paginator.num_pages|add:"-1" %}
            <li>
              <a class="pagination-link"
                 href="?page={{ page_obj.paginator.num_pages }}&search={{ query }}"
                 aria-label="Go to last page"
              >
                {{ page_obj.paginator.num_pages }}
              </a>
            </li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </div>
</div>

hermine/cube/templates/cube/includes/release_tabs.html
<!--
SPDX-FileCopyrightText: 2022 Hermine-team <hermine@inno3.fr>
SPDX-License-Identifier: AGPL-3.0-only
-->
<div class="tabs is-centered is-boxed is-medium">
  <ul>
    <li{% if active_tab == "summary" %} class="is-active"{% endif %}>
      <a href="{% url 'cube:release_summary' release.pk %}">
        <span class="icon is-small"><i class="fas fa-clipboard-list" aria-hidden="true"></i></span>
        <span>Summary</span>
      </a>
    </li>
    {% if perms.cube.change_release_bom %}
      <li{% if active_tab == "import" %} class="is-active"{% endif %}>
        <a href="{% url 'cube:release_import' release.pk %}">
          <span class="icon is-small"><i class="fas fa-upload" aria-hidden="true"></i></span>
          <span>Import components</span>
        </a>
      </li>
    {% endif %}
    <li{% if active_tab == "validation" %} class="is-active"{% endif %}>
      <a href="{% url 'cube:release_validation' release.pk %}">
        <span class="icon is-small"><i class="fas fa-check-double" aria-hidden="true"></i></span>
        <span>Validation steps</span>
      </a>
    </li>
    <li{% if active_tab == "bom" %} class="is-active"{% endif %}>
      <a href="{% url 'cube:release_bom' release.pk %}">
        <span class="icon is-small"><i class="fas fa-book" aria-hidden="true"></i></span>
        <span>Bill of Materials</span>
      </a>
    </li>
    <li {% if active_tab == "obligations" %} class="is-active"{% endif %}>
      <a href="{% url 'cube:release_obligations' release.pk %}">
        <span class="icon is-small"><i class="fas fa-certificate" aria-hidden="true"></i></span>
        <span>Obligations</span>
      </a>
    </li>
  </ul>
</div>